import {
  GetStaticProps,
  type InferGetStaticPropsType,
  type NextPage,
} from 'next';
import Head from 'next/head';
import SingleCountry from '../components/Country';
import { type Country } from '../types/Country';

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  countries,
}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mt-[5rem] flex min-h-[95vh] flex-col items-center p-2'>
        {/* search */}
        {/* filter */}
        <section className='grid w-full grid-cols-[repeat(auto-fill,_300px)] justify-center gap-10'>
          {countries.map(country => (
            <SingleCountry key={country.name.common} country={country} />
          ))}
        </section>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<{
  countries: Country[];
}> = async () => {
  const res = await fetch('https://restcountries.com/v3.1/all');
  const data = await res.json();

  return {
    props: {
      countries: data,
    },
  };
};

export default Home;
