import {
  GetStaticProps,
  type InferGetStaticPropsType,
  type NextPage,
} from 'next';
import Head from 'next/head';
import { useState } from 'react';
import SingleCountry from '../components/Country';
import Search from '../components/Search';
import SearchContextProvider from '../context/SearchContext';
import { type Country } from '../types/Country';

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  data,
}) => {
  const [countries, setCountries] = useState(data);
  const [error, setError] = useState<string | undefined>(undefined);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-[95vh] flex-col items-center gap-5 p-4 pt-[6rem]'>
        <SearchContextProvider
          initialData={data}
          setCountries={setCountries}
          setError={setError}
        >
          <>
            <div className='flex justify-between'>
              <Search />
              {/* filter */}
            </div>
            <section className='grid w-full grid-cols-[repeat(auto-fill,_300px)] justify-center gap-10'>
              {!error &&
                countries.map(country => (
                  <SingleCountry key={country.name.common} country={country} />
                ))}
              {error && (
                <p className='mt-2 text-center text-2xl font-semibold text-blue-very-dark dark:text-white'>
                  {error}
                </p>
              )}
            </section>
          </>
        </SearchContextProvider>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<{
  data: Country[];
}> = async () => {
  const res = await fetch('https://restcountries.com/v3.1/all');
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
};

export default Home;
